# Generated by Django 4.1.7 on 2023-03-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('repository', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('users', models.ManyToManyField(to='users.users')),
            ],
        ),
    ]
