# Generated by Django 4.1.7 on 2023-03-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32, verbose_name='nickname')),
                ('first_name', models.CharField(max_length=32, verbose_name='name')),
                ('last_name', models.CharField(max_length=32, verbose_name='surname')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
            ],
        ),
    ]
